### Send POST request with json body
POST http://127.0.0.1:5000/send_message
Content-Type: application/json

{"user_id": 5556521424, "text": "Поздравляем! Вы зачислены на курс **\"{course_name}\"** автора **{instructor_name}** 🥳n\nДоступ к курсу закроется *{expiry_date}*n\n❗️Чтобы начать обучение, пройдите по ссылке ниже. 👇\nt.me/uz_courstore_student_bot.", "parse_type": "TEXT"}

### Check contact by number
POST http://127.0.0.1:5000/check_contact
Content-Type: application/json

{
  "phone_number": "77785080094"
}
### Check contact by username
POST http://sandbox.courstore.com:5000/check_contact
Content-Type: application/json

{
  "username": "yerkebayevm"
}
### Check contact by user_id
POST http://127.0.0.1:5000/check_contact
Content-Type: application/json

{"user_id":1916038608}

### Check contact by wrong number
POST http://127.0.0.1:5000/check_contact
Content-Type: application/json

{
  "phone_number": "77009809778"
}

### Check contact by wrong number
POST http://127.0.0.1:5000/add_contact
Content-Type: application/json

{
  "phone_number": "+77757937152"
}

### Get settings
GET http://192.168.0.120:5000/settings

### Get settings
GET http://192.168.0.120:5000/start

###
POST http://web.courstore.uz:5000/check_contact
Content-Type: application/json

{"user_id":1360043549}

###
POST http://web.courstore.uz:5000/check_contact
Content-Type: application/json

{ "username": "@SpamBot"}

### Send POST request with json body
POST http://web.courstore.uz:5000/send_message
Content-Type: application/json

{"user_id":1360043549,"text":"Check me"}